//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace live.asp.net {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("live.asp.net.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;
        ///    appInsights.setAuthenticatedUserContext(&quot;{0}&quot;.replace(/[,;=| ]+/g, &quot;_&quot;));
        ///&lt;/script&gt;.
        /// </summary>
        internal static string AppInsightsAuth {
            get {
                return ResourceManager.GetString("AppInsightsAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///        var varSegmentation = 0;
        ///        var varClickTracking = 1;
        ///        var varCustomerTracking = 1;
        ///        var varAutoFirePV = 1;
        ///        var Route = 12656;
        ///        var Ctrl = &quot;&quot;;
        ///
        ///        document.write(&quot;&lt;script type=&apos;text/javascript&apos; src=&apos;https://c.microsoft.com/ms.js&apos;&gt;&lt;\/script&gt;&quot;);
        ///&lt;/script&gt;
        ///&lt;noscript&gt;&lt;img alt=&quot;&quot; width=&quot;1&quot; height=&quot;1&quot; src=&quot;https://c.microsoft.com/trans_pixel.aspx&quot; /&gt;&lt;/noscript&gt;.
        /// </summary>
        internal static string GoogleAnalyticsBody {
            get {
                return ResourceManager.GetString("GoogleAnalyticsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///    (function (i, s, o, g, r, a, m) {
        ///        i[&apos;GoogleAnalyticsObject&apos;] = r; i[r] = i[r] || function () {
        ///            (i[r].q = i[r].q || []).push(arguments)
        ///        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        ///            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        ///    })(window, document, &apos;script&apos;, &apos;https://www.google-analytics.com/analytics.js&apos;, &apos;ga&apos;);
        ///
        ///    ga(&apos;create&apos;, &apos;UA-61337531-1&apos;, &apos;auto&apos;, { &apos;name&apos;: &apos;mscTra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoogleAnalyticsHead {
            get {
                return ResourceManager.GetString("GoogleAnalyticsHead", resourceCulture);
            }
        }
    }
}
